version: '3.9'
services:
  # app:
  #   container_name: app_backend
  #   restart: always
  #   build: ./backend
  #   environment:
  #       - DATABASE_HOST=mongodb://mongo:27017/todos
  #   ports:
  #     - '5000:5000'
  #   volumes:
  #     - ./backend:/data
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo
  # mongo:
  #   volumes:
  #     - /data/db
  #   ports:
  #     - '27017:27017'
  front:
    build: ./calendar-app-front
    volumes:
      - ./calendar-app-front:/app
    ports:
      - "80:80"
  