version: '3.9'
services:
  app:
    restart: always
    build: ./calendar-app-backend
    environment:
        - DATABASE_HOST=mongodb://mongodb:27017/calendar?authSource=admin
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      frontend:
      backend:
  mongodb:
    image: mongo:4.4
    volumes:
      - ./data/mongo:/data/db
    networks:
      backend:
  front:
    build: ./calendar-app-front
    ports:
      - "80:80"
    depends_on:
      - app
    stdin_open: true
    tty: true
    networks:
      frontend:

networks:
  frontend:
  backend:

  